
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
      
# Example configuration.yaml entry
media_player:
  - platform: emby
    host: 192.168.1.208
    api_key: 62812934c03f4fe89bf419f3c4f3eaa6 
    
  - platform: onkyo
    host: 192.168.1.206
    name: DTR40-6
    sources:
      bd-dvd:"Blu-ray"
      tv-cd:"HTPC"
      pc:"Roku"
      cbl-sat:"Comcast"
      game:"Dune"
      STB/DVR:"Control4"
      